### ISSUE TITLE
exported video is lagging

### ISSUE THREAD

**Issue by wdcs-harshlathigara** [polarby/render#10] opened 2023-03-30 09:17 UTC
**Describe the bug**
i have created video with the help of render package but video is so much lagging 
a widget that i want to render in video its contains some text widget with animation 

**Expected behavior**
video should play smooth.

**Comment by polarby** [comment] 2023-03-30 10:24
This package is very well documented, please refer to the [Using settings to keep up performance](https://pub.dev/packages/render#limitations-and-performance) heading to check what you can do to keep performing at high quality. Due to hardware limitations, you must compensate for either the process duration, video quality, or fluency (what you have described). I recommend taking longer rendering time instead of fluency.

I have thought about making automatically adjusted settings (where you just set your preferences of compensation), but it is hard to find documentation to check the current FPS of the device. I wasn't able to archive that yet.

I am gonna close this issue, as I think generally this is a settings issue. If you want to get invested in building an automatic solution, please don't hesitate to reach out to me for help (eg. pull request).

**Comment by wdcs-harshlathigara** [comment] 2023-03-31 11:12
yes i have checked your documentation and i have tested will all possible combination but unable to achieve desired output

**Comment by polarby** [comment] 2023-04-01 04:02
Could you please provide me with a mockup code of what you are trying to archive? If your UI widget is big, it might also be unnecessary to set a high `pixel ratio`.

I recommend you lower the `pixelRatio` and lower the `simultaneousCaptureHandlers` while setting your `frameRate` to your desired output. Then slowly adjust settings to fit even more to your needs, without lagging.

Note that lagging is not caused by the post-capturing processing, but by too many simultaneous processes during capturing,  which makes the whole application lose its frame rate and therefore also the UI images that can be repainted (due to too many handlers, images being stored, etc.). Therefore, it is critical to keep the device framerate high, while post-processing usually can help you out by adjusting the image quality through upscaling.

**Closed** 2023-05-10 02:40 UTC
Labels: bug
