### ISSUE TITLE
Duplicate class import error with ffmpeg package

### ISSUE THREAD

**Issue by rlee1990** [polarby/render#8] opened 2023-01-28 16:22 UTC
Hi is is possible to use the ffmpeg_kit_flutter instead of the one used in this package?
It causes issues with other packages that all use ffmpeg_kit_flutter.

**Comment by polarby** [comment] 2023-01-28 16:26
Hi, 
`Render`uses `ffmpeg_kit_flutter_https_gpl`, which is a sub-package of `ffmpeg_kit_flutter`. Could you please provide the errors you are getting?
I suspect this is an import issue , wich would mean you need to change the imports a bit:

Example: Instead of 
```
import 'package:flutter/services.dart';
```
do:
```
import 'package:flutter/services.dart' as service;

service.yourMethod();

```

**Comment by rlee1990** [comment] 2023-01-28 16:27
The error I get is
`Duplicate class com.arthenica.ffmpegkit.Statistics found in modules jetified-ffmpeg-kit-https-5.1-runtime`

**Comment by polarby** [comment] 2023-01-28 16:29
Ok got it. Have you tried changing the imports, like i have shown? In case this resolves this, i will adjust the import line in `Render`package, so you can import like you would do normally....

**Comment by rlee1990** [comment] 2023-01-28 16:31
> Ok got it. Have you tried changing the imports, like i have shown? In case this resolves this, i will adjust the import line in `Render`package, so you can import like you would do normally....

Should I be changing them in your package or in the code I write because I don't directly use the services import

**Comment by polarby** [comment] 2023-01-28 16:33
No the import in your code. Sorry, the `service` import was just an example. Change your Ffmepg / `video_trimmer`import like the example.

**Comment by rlee1990** [comment] 2023-01-28 16:36
Nope it still fails to build the application:
```
A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.arthenica.ffmpegkit.Abi found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.AbiDetect found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.AbstractSession found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.AsyncFFmpegExecuteTask found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.AsyncFFprobeExecuteTask found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.AsyncGetMediaInformationTask found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.BuildConfig found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.CameraSupport found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.Chapter found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFmpegKit found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFmpegKitConfig found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFmpegKitConfig$1 found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFmpegKitConfig$2 found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFmpegKitConfig$SAFProtocolUrl found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFmpegSession found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFmpegSessionCompleteCallback found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFprobeKit found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFprobeSession found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.FFprobeSessionCompleteCallback found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.Level found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.Log found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.LogCallback found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.LogRedirectionStrategy found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.MediaInformation found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.MediaInformationJsonParser found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.MediaInformationSession found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.MediaInformationSessionCompleteCallback found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.NativeLoader found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.Packages found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.ReturnCode found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.Session found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.SessionState found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.Signal found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.Statistics found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.StatisticsCallback found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
     Duplicate class com.arthenica.ffmpegkit.StreamInformation found in modules jetified-ffmpeg-kit-https-5.1-runtime (com.arthenica:ffmpeg-kit-https:5.1) and jetified-ffmpeg-kit-https-gpl-5.1-runtime (com.arthenica:ffmpeg-kit-https-gpl:5.1)
```

**Comment by polarby** [comment] 2023-01-28 16:38
Thanks for the issue. Could you provide me with a quick and dirty example with video_trimmer import so i can run it and debug it?

**Comment by rlee1990** [comment] 2023-01-28 16:42
Sure Ill get started on that right now

**Comment by polarby** [comment] 2023-01-28 16:42
Also, can you check if [this](https://stackoverflow.com/a/54680454/11003497) solution helps? This might be a multi dex issue and not related to this plugin.

**Comment by rlee1990** [comment] 2023-01-28 16:47
> Also, can you check if [this](https://stackoverflow.com/a/54680454/11003497) solution helps? This might be a multi dex issue and not related to this plugin.

Yup I tried it and it still doesn't work. I will leave that in the example also.

**Comment by rlee1990** [comment] 2023-01-28 16:52
Okay the quick example is just a fork of your example and I added the video_trimmer package without using it in the code and get the errors still:
[https://github.com/rlee1990/render](https://github.com/rlee1990/render)

**Comment by polarby** [comment] 2023-01-28 16:54
Alright, I am on it, it might take some time!

**Comment by rlee1990** [comment] 2023-01-28 16:55
I also just did a test with the fork without deploying it back to github were I switched the FFMPEG to use the same one in video_trimmer and its working without an issue.

**Comment by polarby** [comment] 2023-01-28 20:40
I was not able to find a satisfying solution for this error. It appears this is a problem happens always if there are multiple FFmpeg instances within one project. This can either be by multiple plugins imports that use Ffmpeg or a plugin with FFmpeg usage and own FFmpeg import. I am not sure if this error also appears with other plugins. This error **will happen with any plugin**, when you use multiple instances like this. 

## What needs to be done?
As far as my research goes so far, there is no current appropriate resolution to this problem. As this is a double import problem of two different versions, a possible solution is to sync the Ffmpeg version number (which is not always easy, as some operations require different ffmpeg version). 
It would be great to isolate the plugins that are used within a package, but I am not aware of any way to do this.


In this specific issue we have both a `jetified-ffmpeg-kit-https-gpl-5.1`(used by `Render`) and the `jetified-ffmpeg-kit-https-5.1`(used by `video_trimmer`) FFmpeg usage: 
```
2 files found with path 'lib/arm64-v8a/libavcodec.so' from inputs:
      - /Users/myName/.gradle/caches/transforms-3/29473f64bb3a0e5823587658e804b0da/transformed/jetified-ffmpeg-kit-https-gpl-5.1/jni/arm64-v8a/libavcodec.so
      - /Users/myName/.gradle/caches/transforms-3/ac7665f545673455679b57f9a4d09ae7/transformed/jetified-ffmpeg-kit-https-5.1/jni/arm64-v8a/libavcodec.so
```
As `jetified-ffmpeg-kit-https-gpl-5.1` includes `jetified-ffmpeg-kit-https-5.1`, it is possible to remove the import of the lower package and therefore only depend on one -the higher-  import. Therefore in the following I will give a standardized solution to how to resolve it by correcting the imports:

## Dirty solution

1. Find the package with the denominator import (highest import, with most functions -> in this case `jetified-ffmpeg-kit-https-gpl-5.1`, see hierarchy [ffmpeg packages](https://github.com/arthenica/ffmpeg-kit#9-packages))

Do the the following procedure for all sub import plugins

2. `git clone <url to package> ./lib/package_name_copy` (for the render example flutter project `./example/lib` -> `git clone https://github.com/sbis04/video_trimmer ./example/lib/video_trimmer_copy`)
3. Manually go to `./lib/package_name_copy/pubspec.yaml` and change the ffmpeg dependency to the denominator one (in our case ` ffmpeg_kit_flutter_https_gpl: ^5.1.0`)
4. run flutter clean & flutter pub get

Note that you will archive the current version of this package to a local directory. This is a dirty solution as updating needs to be done manually like the described solution,  and therefore can only be maintained with very few packages (aka `Render`and `Video_trimmer`). 

If you find a better solution I would like to ask you to post it here as well so others can maybe do a cleaner import resolution.

## Same issues
Just for references, here are issues that have the exact same problem:
- [Execution failed for task ':app:checkDebugDuplicateClasses'](https://github.com/sbis04/video_trimmer/issues/158)
- [Duplicate class issue](https://github.com/arthenica/ffmpeg-kit/issues/368)
- [Duplicate Class Error](https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/679)
- [Duplicate class using integration test](https://github.com/flutter/flutter/issues/107235)
- [How to fix ':app:checkDebugDuplicateClasses' error in flutter](https://stackoverflow.com/questions/73781237/how-to-fix-appcheckdebugduplicateclasses-error-in-flutter)


Here are problems with same issues and with solutions, that I could not reproduce:
- [Execution failed for task ':app:checkDebugDuplicateClasses'](https://github.com/sbis04/video_trimmer/issues/128)
- [Duplicate class I'm already using ffmpeg_kit_flutter_audio in my code: 5.1.0-LTS for audio conversion](https://github.com/sbis04/video_trimmer/issues/190)

**Comment by polarby** [comment] 2023-01-28 20:41
I am gonna close this issue for now, as there is a temporary solution. Please be sure to update this issue if there is a better alternative!!!

**Closed by polarby** 2023-01-28 20:41 UTC
Labels: bug

**Comment by rlee1990** [comment] 2023-01-28 20:48
@polarby is there a reason why you don't use the same exact package of ffmpeg as video_trimmer?

**Comment by polarby** [comment] 2023-01-28 20:56
Yes, in order to work with the audio conversion the `x264` of the `https-gpl` (`http`, which `video_trimmer` uses is not enough) is required:

https://github.com/polarby/render/blob/e110fce6cc4bf074319ebc6d441039571b595082/lib/src/formats/abstract.dart#L128-L131

I am sorry that there currently isn't a better way to do this, but I hope that you still decide to take advantage of the great functions of FFmpeg.

**Comment by rlee1990** [comment] 2023-01-28 20:59
@polarby thanks good to know. I am keeping the package and looking for alternatives for video_trimmer that will work.
